# Generated by Django 3.1.7 on 2021-02-21 04:46

from django.db import migrations, models

def split_name(apps, schema_editor):
    """
    convert "name" -> "first_name", "last_name"
    """
    Developer = apps.get_model("devdb", "Developer")

    # Split names into first name/last name
    for dev in Developer.objects.all():
        names = dev.name.split()
        if len(names) == 2:
            dev.first_name, dev.last_name = names
        else:
            print(names)
            breakpoint()
        dev.save()

def join_name(apps, schema_editor):
    Developer = apps.get_model("devdb", "Developer")

    # Join names into one field
    for dev in Developer.objects.all():
        dev.name = dev.first_name + " " + dev.last_name
        dev.save()





class Migration(migrations.Migration):

    dependencies = [
        ('devdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='first_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developer',
            name='last_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.RunPython(split_name, join_name),
        migrations.RemoveField(
            model_name='developer',
            name='name',
        ),
    ]
